apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudpool-ingress
  namespace: cloudpool
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.cloudpool.dev
      secretName: cloudpool-tls
  rules:
    - host: api.cloudpool.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloudpool-api
                port:
                  number: 8080