apiVersion: v1
kind: Secret
metadata:
  name: cloudpool-secrets
  namespace: cloudpool
type: Opaque
data:
  database-user: cGxhY2Vob2xkZXJfdXNlcg==
  database-password: cGxhY2Vob2xkZXJfcGFzc3dvcmQ=
  jwt-secret: cGxhY2Vob2xkZXJfand0X3NlY3JldF9rZXk=
  google-drive-client-id: cGxhY2Vob2xkZXJfY2xpZW50X2lk
  google-drive-client-secret: cGxhY2Vob2xkZXJfY2xpZW50X3NlY3JldA==
  openai-api-key: cGxhY2Vob2xkZXJfb3BlbmFpX2FwaV9rZXk=
